### ISSUE TITLE
Prevent jump lines

### ISSUE THREAD

**Issue by pols63** [sibiraj-s/vscode-scss-formatter#15]
Hi, I like the tool.

But, I would like that when applying the format to my code, it would not insert or remove the line breaks that it already has. It should only affect spaces and indentation tabs.

Thanks.

**Comment by sibiraj-s** [comment]
Hi @pols63,

I understand what you want, but this extension uses [prettier](https://prettier.io/) under the hood to format the files. So only the options supported by prettier is supported here. Any formatting behaviour change, you might want to open an issue at prettier. And also please refer their [Option Philosophy](https://prettier.io/docs/en/option-philosophy.html) once.

I am closing this issue, since I can't do anything here. Feel free to continue the conversation if required. Thanks.
